// // const topics = [
// //   "Dark Psychology Tricks People Use On You",
// //   "Signs Someone Is Manipulating You",
// //   "How Your Brain Tricks You Every Day",
// //   "Psychology Of Attraction Explained",
// //   "Why You Procrastinate And How To Stop",
// //   "Mind Control Techniques You Dont Know",
// //   "How To Read Anyone Instantly",
// //   "Signs Of A Narcissist Around You",
// //   "Why Smart People Feel Lonely",
// //   "The Psychology Behind Lying",
// //   "How To Manipulate Your Own Mind",
// //   "Why People Stay In Toxic Relationships",
// //   "Secret Psychology Of Body Language",
// //   "How Advertisers Control Your Mind",
// //   "Psychology Tricks To Be More Confident",
// //   "Why You Always Feel Not Good Enough",
// //   "The Dark Side Of Social Media",
// //   "How To Spot A Fake Person Instantly",
// //   "Why Your Brain Loves Bad Habits",
// //   "Psychology Of Money And Happiness",
// //   "Signs You Are Emotionally Intelligent",
// //   "How To Make Anyone Like You",
// //   "Why People Become Obsessed With Others",
// //   "The Science Of First Impressions",
// //   "How Trauma Changes Your Personality",
// //   "Why Introverts Are Secretly Powerful",
// //   "Psychology Of Fear And How To Beat It",
// //   "Signs Someone Is Secretly Jealous Of You",
// //   "How To Stop Overthinking Forever",
// //   "The Psychology Of Revenge",
// //   "Why We Fall For The Wrong People",
// //   "How Your Childhood Affects You Now",
// //   "Signs Of High Intelligence You Ignore",
// //   "Psychology Behind Self Sabotage",
// //   "How To Win Any Argument Psychologically",
// //   "Why People Ghost Others Explained",
// //   "The Science Of Habits And Willpower",
// //   "How To Read Hidden Emotions",
// //   "Psychology Of Dreams And What They Mean",
// //   "Why Rejection Hurts Like Physical Pain",
// // ];

// // function getRandomTopic() {
// //   const index = Math.floor(Math.random() * topics.length);
// //   return topics[index];
// // }

// // module.exports = { getRandomTopic };

// // const topics = [

// // /* ================= DARK PSYCHOLOGY & MIND (40 - Original) ================= */

// // "Dark Psychology Tricks People Use On You",
// // "Signs Someone Is Manipulating You",
// // "How Your Brain Tricks You Every Day",
// // "Psychology Of Attraction Explained",
// // "Why You Procrastinate And How To Stop",
// // "Mind Control Techniques You Dont Know",
// // "How To Read Anyone Instantly",
// // "Signs Of A Narcissist Around You",
// // "Why Smart People Feel Lonely",
// // "The Psychology Behind Lying",
// // "How To Manipulate Your Own Mind",
// // "Why People Stay In Toxic Relationships",
// // "Secret Psychology Of Body Language",
// // "How Advertisers Control Your Mind",
// // "Psychology Tricks To Be More Confident",
// // "Why You Always Feel Not Good Enough",
// // "The Dark Side Of Social Media",
// // "How To Spot A Fake Person Instantly",
// // "Why Your Brain Loves Bad Habits",
// // "Psychology Of Money And Happiness",
// // "Signs You Are Emotionally Intelligent",
// // "How To Make Anyone Like You",
// // "Why People Become Obsessed With Others",
// // "The Science Of First Impressions",
// // "How Trauma Changes Your Personality",
// // "Why Introverts Are Secretly Powerful",
// // "Psychology Of Fear And How To Beat It",
// // "Signs Someone Is Secretly Jealous Of You",
// // "How To Stop Overthinking Forever",
// // "The Psychology Of Revenge",
// // "Why We Fall For The Wrong People",
// // "How Your Childhood Affects You Now",
// // "Signs Of High Intelligence You Ignore",
// // "Psychology Behind Self Sabotage",
// // "How To Win Any Argument Psychologically",
// // "Why People Ghost Others Explained",
// // "The Science Of Habits And Willpower",
// // "How To Read Hidden Emotions",
// // "Psychology Of Dreams And What They Mean",
// // "Why Rejection Hurts Like Physical Pain",

// // /* ================= CHILDREN NEW (50) ================= */

// // "Why Some Babies Are Born Smarter Than Others",
// // "The Hidden Danger of Praising Kids Too Much",
// // "Why Children Lie And What It Actually Means",
// // "How Birth Order Shapes A Child's Personality Forever",
// // "The Real Reason Kids Are Afraid Of The Dark",
// // "Why Children Copy Everything Adults Do",
// // "How Music Changes A Child's Brain Permanently",
// // "Why Some Kids Are More Sensitive Than Others",
// // "The Science Behind Why Kids Love Superheroes",
// // "Why Arguing In Front Of Kids Damages Them",
// // "How A Child's Name Affects Their Future",
// // "Why Kids Are Brutally Honest And Cannot Lie Well",
// // "The Truth About How Sugar Actually Affects Kids",
// // "Why Children Prefer One Parent Over The Other",
// // "How Loneliness In Childhood Shapes Adult Life",
// // "Why Kids Ask The Same Question Over And Over",
// // "The Shocking Effect Of Yelling At Children",
// // "Why Some Kids Are Natural Born Leaders",
// // "How Playing Outside Changes A Child's Brain",
// // "Why Children Dream More Than Adults",
// // "The Real Reason Teenagers Push Parents Away",
// // "How A Difficult Childhood Creates Stronger Adults",
// // "Why Kids Fear Monsters Under The Bed",
// // "The Science Of Why Kids Hate Vegetables",
// // "How Reading To Babies Changes Their Intelligence",
// // "Why Children Laugh 300 Times More Than Adults",
// // "The Surprising Link Between Boredom And Creativity In Kids",
// // "Why Some Kids Talk To Themselves Constantly",
// // "How Divorce Permanently Changes A Child's Brain",
// // "Why Children Develop Phobias So Easily",
// // "The Real Reason Kids Need Routines To Feel Safe",
// // "Why Boys And Girls Brains Develop Differently",
// // "How Poverty Changes A Child's Brain Structure",
// // "Why Some Kids Are Night Owls From Birth",
// // "The Hidden Damage Of Overprotecting Your Child",
// // "Why Children Forget Painful Memories Faster",
// // "How A Teacher's Attitude Shapes A Child Forever",
// // "Why Kids Get Attached To Specific Toys",
// // "The Science Of Imaginary Friends In Children",
// // "Why Children Are Better At Learning New Skills",
// // "How Siblings Shape Each Other's Personalities",
// // "Why Kids Believe In Magic So Easily",
// // "The Truth About How Video Games Affect Young Brains",
// // "Why Children Are More Resilient Than We Think",
// // "How Hunger Affects A Child's Ability To Learn",
// // "Why Kids Wake Up Earlier Than Adults Naturally",
// // "The Real Reason Children Cry Without Knowing Why",
// // "How Colors Affect A Child's Mood And Behavior",
// // "Why Some Children Are Born Empaths",
// // "The Shocking Effect Of Too Much Screen Time On Children",

// // /* ================= FOOD NEW (50) ================= */

// // "Why You Eat More When You're With Other People",
// // "The Food That Is Scientifically More Addictive Than Cocaine",
// // "Why Eating Slowly Makes You Lose Weight Faster",
// // "How Your Mood Is Controlled By What You Eat",
// // "The Real Reason Breakfast Is The Most Dangerous Meal",
// // "Why Your Gut Bacteria Controls Your Mental Health",
// // "How Eating At Night Destroys Your Body Slowly",
// // "The Shocking Truth About So-Called Natural Foods",
// // "Why Certain Smells Make You Instantly Hungry",
// // "How Restaurants Trick You Into Spending More",
// // "The Real Reason Diets Always Fail",
// // "Why Your Body Craves Specific Foods When Sick",
// // "How Ultra Processed Food Rewires Your Brain",
// // "The Truth About Detox Diets Nobody Tells You",
// // "Why Eating Alone Makes You Eat More",
// // "How Food Companies Engineer Food To Be Addictive",
// // "The Surprising Foods That Destroy Your Sleep Quality",
// // "Why Your Body Rejects Healthy Food At First",
// // "How Stress Changes What Your Body Does With Food",
// // "The Real Reason You Feel Tired After Eating",
// // "Why Humans Are The Only Animals That Cook Food",
// // "How What You Eat Changes Your DNA Over Time",
// // "The Shocking Amount Of Sugar In Foods Labeled Healthy",
// // "Why Spicy Food Makes You Feel Good",
// // "How Fasting For One Day Changes Your Body",
// // "The Truth About Superfoods The Industry Hides",
// // "Why Your Cravings Are Not About Hunger",
// // "How Dehydration Is Mistaken For Hunger",
// // "The Real Reason Chocolate Makes You Feel Better",
// // "Why Some People Can Eat Anything And Stay Thin",
// // "How Your Eyes Control How Much You Eat",
// // "The Dangerous Truth About Energy Drinks",
// // "Why Food Tastes Different When You Are Sick",
// // "How Your Gut Sends Signals Directly To Your Brain",
// // "The Real Science Behind Why We Love Comfort Food",
// // "Why Eating Together As A Family Changes Everything",
// // "How Intermittent Fasting Rewires Your Brain",
// // "The Foods That Are Proven To Kill Depression",
// // "Why Your Stomach Growls And What It Really Means",
// // "How Alcohol Destroys Your Body From The Inside",
// // "The Real Reason You Always Have Room For Dessert",
// // "Why Coffee Does Not Actually Wake You Up",
// // "How Your Childhood Food Habits Control You Today",
// // "The Truth About Fat That Science Got Wrong For Years",
// // "Why Eating Colors Matters More Than You Know",
// // "How Food Affects Your Skin More Than Skincare Does",
// // "The Reason You Cannot Stop Eating Certain Foods",
// // "Why Humans Are Hardwired To Love Sweet Foods",
// // "How Your Microbiome Controls Your Food Decisions",
// // "The Shocking Link Between Food And Your Mood",

// // /* ================= ORGAN NEW (50) ================= */

// // "The Organ That Can Regrow Itself After Being Cut",
// // "Why Your Heart Skips A Beat When You Are Shocked",
// // "How Your Brain Decides What You Notice And What You Miss",
// // "The Real Reason Your Stomach Makes Noises",
// // "Why Your Eyes Twitch When You Are Tired",
// // "How Your Kidneys Save Your Life Every Single Minute",
// // "The Shocking Speed At Which Your Skin Replaces Itself",
// // "Why Your Lungs Are Never Fully Empty",
// // "How Your Tongue Is The Strongest Muscle You Have",
// // "The Real Reason Your Ears Never Stop Working",
// // "Why Your Brain Uses More Energy Than Any Other Organ",
// // "How Your Nose Can Detect Over One Trillion Smells",
// // "The Truth About What Your Appendix Actually Does",
// // "Why Your Heart Beats Faster When You Fall In Love",
// // "How Your Liver Performs Over 500 Functions Daily",
// // "The Organ That Works Hardest While You Sleep",
// // "Why Your Eyes See The World Upside Down First",
// // "How Your Spine Controls More Than Just Your Back",
// // "The Real Reason Your Hair Turns Grey Under Stress",
// // "Why Your Immune System Sometimes Attacks Itself",
// // "How Your Blood Changes Color Inside Your Body",
// // "The Shocking Electrical Activity In Your Heart",
// // "Why Your Brain Shrinks When You Are Dehydrated",
// // "How Your Stomach Acid Can Dissolve Metal",
// // "The Real Reason Your Bones Are Stronger Than Steel",
// // "Why Your Pupils Change Size Without You Knowing",
// // "How Your Intestines Would Stretch Over 7 Meters",
// // "The Truth About What Happens To Your Body After Death",
// // "Why Your Brain Keeps Working Even When You Are Unconscious",
// // "How Your Pancreas Controls Every Mood You Have",
// // "The Real Reason Your Fingernails Keep Growing",
// // "Why Your Left And Right Lungs Are Different Sizes",
// // "How Your Brain Rewires Itself After An Injury",
// // "The Shocking Thing Your Body Does When You Are Embarrassed",
// // "Why Your Eardrums Can Detect One Billionth Of A Meter",
// // "How Your Liver Knows When You Are Drinking Alcohol",
// // "The Real Reason Your Body Temperature Drops At Night",
// // "Why Your Brain Is 73 Percent Water",
// // "How Your Heart Changes Shape Under Extreme Stress",
// // "The Truth About What Your Gallbladder Actually Does",
// // "Why Your Spleen Is Called The Blood Graveyard",
// // "How Your Thyroid Controls Your Entire Personality",
// // "The Real Reason Your Muscles Burn During Exercise",
// // "Why Your Brain Has A Built In Reward System",
// // "How Your Body Produces Its Own Natural Painkillers",
// // "The Organ That Has More Nerve Endings Than Your Brain",
// // "Why Your Body Stores Fat In Specific Places",
// // "How Your Heart Knows When You Are Stressed Before You Do",
// // "The Shocking Number Of Cells Your Body Kills Every Second",
// // "Why Your Body Is Actually Mostly Empty Space",

// // /* ================= PSYCHOLOGY NEW (50) ================= */

// // "Why You Remember Bad Memories Better Than Good Ones",
// // "The Real Reason You Talk To Yourself In Your Head",
// // "How Loneliness Physically Damages Your Brain",
// // "Why You Feel Guilty Even When You Did Nothing Wrong",
// // "The Psychology Behind Why People Follow Cults",
// // "How Your Personality Changes Depending On Who You Are With",
// // "Why You Cannot Tickle Yourself — The Weird Science",
// // "The Real Reason People Believe In Conspiracy Theories",
// // "How Silence Can Be A Powerful Psychological Weapon",
// // "Why You Always Remember Unfinished Tasks More",
// // "The Psychology Of Why People Are Mean Online",
// // "How Color Affects Your Mood Without You Realizing",
// // "Why Your Brain Cannot Tell Difference Between Real And Imagined",
// // "The Real Reason You Feel Watched When Alone",
// // "How Power Changes A Person's Brain Permanently",
// // "Why People With High IQ Struggle With Daily Life",
// // "The Science Of Why You Hate The Sound Of Your Own Voice",
// // "How Boredom Is Actually Good For Your Brain",
// // "Why You Make Worse Decisions When You Are Hungry",
// // "The Real Reason People Are Afraid Of Success",
// // "How Music Unlocks Memories That Nothing Else Can",
// // "Why You Find It Easier To Lie In Text Than In Person",
// // "The Psychology Of Why We Procrastinate On Big Goals",
// // "How Stress Makes You More Likely To Make Mistakes",
// // "Why Your Brain Is Hardwired To Expect The Worst",
// // "The Real Reason We Cry At Movies And Songs",
// // "How Sleep Deprivation Makes You Psychologically Dangerous",
// // "Why Helping Others Makes You Feel Better Than Helping Yourself",
// // "The Shocking Effect Of Compliments On The Brain",
// // "How Nostalgia Affects Your Brain Chemistry",
// // "Why You Feel Anxious For No Reason At All",
// // "The Real Psychology Behind Road Rage",
// // "How Your Brain Changes When You Fall In Love",
// // "Why Humans Fear Death But Animals Do Not",
// // "The Psychology Of Why We Judge Others Instantly",
// // "How Repetition Tricks Your Brain Into Believing Lies",
// // "Why Some People Never Feel Satisfied No Matter What",
// // "The Real Reason Eye Contact Makes People Uncomfortable",
// // "How Your Subconscious Mind Makes Decisions Before You Do",
// // "Why People Who Swear Are Proven To Be More Honest",
// // "The Dark Psychology Behind Why People Cheat",
// // "How Anger Can Actually Be Healthy For Your Brain",
// // "Why Your Memory Is Less Reliable Than You Think",
// // "The Real Reason People Love Horror Movies",
// // "How Meditation Permanently Changes Your Brain Structure",
// // "Why We Trust Attractive People More Without Realizing",
// // "The Science Of Why Humans Need To Belong",
// // "How Chronic Stress Slowly Destroys Your Intelligence",
// // "Why You Feel Like Everyone Is Watching You",
// // "The Psychology Of Why We Cannot Stop Scrolling",

// // /* ================= DAILY BODY NEW (50) ================= */

// // "Why Your Body Shakes When You Are Cold",
// // "The Real Reason You Sweat Even When You Are Not Hot",
// // "Why Your Voice Sounds Different On A Recording",
// // "How Your Body Knows What Time It Is Without A Clock",
// // "The Real Reason You Get Butterflies In Your Stomach",
// // "Why You Cannot Hold Your Breath Forever",
// // "How Your Body Produces Enough Energy To Power A Light Bulb",
// // "The Real Reason Your Skin Wrinkles In Water",
// // "Why Your Heart Rate Changes When You Are Nervous",
// // "How Your Body Heals A Cut Without You Doing Anything",
// // "The Real Reason You Get Chills From Music",
// // "Why Humans Are The Only Animals That Blush",
// // "How Your Body Fights Viruses While You Sleep",
// // "The Real Reason You Get Brain Freeze From Cold Food",
// // "Why Your Eyes Are Closed When You Sneeze",
// // "How Holding In A Sneeze Can Be Deadly",
// // "The Real Reason Your Stomach Growls In Meetings",
// // "Why You Feel Heavier When You Wake Up",
// // "How Your Body Tells You It Needs Water Before You Feel Thirsty",
// // "The Real Reason People Faint When They See Blood",
// // "Why Your Legs Jerk When You Fall Asleep",
// // "How Your Body Produces Its Own Alcohol Naturally",
// // "The Real Reason You Get Dark Circles Under Your Eyes",
// // "Why Your Body Temperature Drops Right Before Sleep",
// // "How Laughter Genuinely Heals Your Body From Inside",
// // "The Real Reason You Cannot See Your Own Blind Spot",
// // "Why Your Heart Is On The Left Side Of Your Chest",
// // "How Your Body Detects Danger Before Your Brain Does",
// // "The Real Reason Your Joints Crack When You Stretch",
// // "Why You Get Hiccups And How To Actually Stop Them",
// // "How Your Body Changes When You Hold Someone's Hand",
// // "The Real Reason You Feel Pain In A Limb That Is Missing",
// // "Why Humans Are The Only Animals That Cry Emotional Tears",
// // "How Your Body Knows To Wake Up Before Your Alarm",
// // "The Real Reason You Forget Why You Walked Into A Room",
// // "Why Your Nose Always Has One Nostril More Open Than The Other",
// // "How Your Body Burns Calories Even While Sitting Still",
// // "The Real Reason You Feel Sick When You Read In A Car",
// // "Why Your Heartbeat Syncs With People You Trust",
// // "How Your Body Reacts To Eye Contact With A Stranger",
// // "The Real Reason You Get Hungry At The Same Time Every Day",
// // "Why Your Eyes Move Rapidly When You Are Dreaming",
// // "How Your Body Produces More Tears When You Hold Them In",
// // "The Real Reason Your Feet Smell Worse Than Other Body Parts",
// // "Why You Feel More Pain When You Expect It",
// // "How Your Body Knows When Someone Is Staring At You",
// // "The Real Reason You Feel Relaxed After Crying",
// // "Why Your Heart Beats Faster When You Hear Your Name",
// // "How Your Body Ages Faster When You Are Lonely",
// // "The Real Reason You Feel Exhausted After Doing Nothing",
// // "Interesting Facts About Human Reproduction",
// // "Why Physical Intimacy Improves Mental Health",
// // "Facts About Hormones And Relationships",
// // "Why Communication Is Important In Relationships",
// // "The Science Behind Attraction",
// // "Why Couples Who Laugh Together Stay Together",
// // "How Love Affects Your Brain",
// // "Why Trust Is Important In Relationships",
// // "Facts About Marriage And Happiness",
// // "How Emotional Connection Strengthens Relationships",
// // "Why People Fall In Love",
// // "How Relationships Affect Mental Health",
// // "The Psychology Of Romantic Attraction",
// // "Why Respect Matters In Relationships",
// // "How Healthy Relationships Improve Life",
// // "Why Companionship Is Important For Humans",
// // "The Science Of Emotional Bonding",
// // "Why Love Reduces Stress",
// // "How Relationships Improve Longevity",
// // "The Benefits Of Emotional Support",
// // /* ================= RELATIONSHIP NEW (30) ================= */

// // "Why People Cheat Even When They Are Happy",
// // "The Real Reason Couples Fight About Small Things",
// // "How To Tell If Someone Likes You Without Them Saying It",
// // "Why Love Feels Like A Drug In Your Brain",
// // "The Science Of Why We Miss People We Hate",
// // "How Couples Unconsciously Mirror Each Other",
// // "Why Relationships Change After Having Children",
// // "The Real Reason Breakups Hurt More Than Physical Injuries",
// // "How Attachment Style Formed In Childhood Controls Love Life",
// // "Why We Always Want What We Cannot Have",
// // "The Psychology Behind Why People Stay With Narcissists",
// // "How Social Media Is Destroying Modern Relationships",
// // "Why Arguments In Relationships Never Solve Anything",
// // "The Real Reason People Fall Out Of Love Slowly",
// // "How Jealousy Actually Destroys What You Fear Losing",
// // "Why We Idealize People Before We Really Know Them",
// // "The Science Of Why Long Marriages Survive",
// // "How Physical Touch Affects Your Mental Health Daily",
// // "Why We Are Attracted To People Who Look Like Our Parents",
// // "The Real Reason Affairs Destroy More Than Just Relationships",
// // "How Kindness Can Be A Form Of Manipulation",
// // "Why People Who Love Hard Get Hurt The Most",
// // "The Real Science Of Why Opposites Attract",
// // "How Unhealed Wounds Make You Attract Wrong People",
// // "Why Being Too Available Kills Attraction",
// // "The Real Reason Some People Cannot Be Alone",
// // "How Gaslighting Changes Your Sense Of Reality",
// // "Why Love Bombing Is More Dangerous Than Hate",
// // "The Real Reason Chemistry Fades In Long Relationships",
// // "How Your Relationship With Your Parents Controls Your Love Life",

// // /* ================= SLEEP AND DREAMS NEW (30) ================= */

// // "Why You Cannot Run In Your Dreams",
// // "The Real Reason Some People Never Dream",
// // "How Sleeping Less Than 6 Hours Changes Your Personality",
// // "Why You Feel More Tired After A Long Sleep",
// // "The Shocking Things That Happen To Your Brain During Nightmares",
// // "Why You Cannot Read Text In Your Dreams",
// // "How Napping For 20 Minutes Beats 2 Hours Of Extra Sleep",
// // "The Real Reason You Talk In Your Sleep",
// // "Why Blind People Dream Differently Than Sighted People",
// // "How Your Brain Sorts Your Memories While You Sleep",
// // "The Real Reason You Fall In Dreams And Jerk Awake",
// // "Why Some People Experience The Same Dream Repeatedly",
// // "How Missing One Night Of Sleep Ages Your Brain By Years",
// // "The Real Reason Dreams Feel So Real",
// // "Why You Cannot Die In Your Dreams",
// // "How Your Brain Creates Entirely New Faces In Dreams",
// // "The Real Reason Night Shift Workers Die Younger",
// // "Why Animals Dream Just Like Humans Do",
// // "How The Position You Sleep In Affects Your Dreams",
// // "The Real Reason You Cannot Remember Most Of Your Dreams",
// // "Why Sleeping Next To Someone Changes Your Sleep Quality",
// // "How Your Brain Is More Active In Some Parts Of Sleep",
// // "The Real Reason Children Need More Sleep Than Adults",
// // "Why You Dream Of Falling From Heights",
// // "How Eating Before Bed Changes What You Dream About",
// // "The Real Reason Teenagers Cannot Wake Up Early",
// // "Why People Who Sleep Less Live Shorter Lives",
// // "How Dreams Solve Problems Your Waking Brain Cannot",
// // "The Real Reason Full Moons Affect Your Sleep",
// // "Why You Always Wake Up Just Before Your Alarm",

// // ];
// const topics = [

// /* ================= HORMONES & BODY CHEMISTRY (25) ================= */
// "Why Your Hormones Control Every Decision You Make",
// "The Hormone That Makes You Fall In Love Instantly",
// "Why Cortisol Is Slowly Destroying Your Body",
// "How Dopamine Makes You Addicted To Your Phone",
// "The Hormone That Makes You Trust Strangers",
// "Why Adrenaline Can Give You Superhuman Strength",
// "How Serotonin Controls Your Mood Without You Knowing",
// "The Real Reason Your Hormones Crash After 30",
// "Why Melatonin Does More Than Just Help You Sleep",
// "How Insulin Controls More Than Just Your Blood Sugar",
// "The Hormone That Makes You Feel Empty After Eating",
// "Why Testosterone Is Not Just A Male Hormone",
// "How Estrogen Affects Your Brain Every Single Day",
// "The Hormone Behind Every Panic Attack You Have",
// "Why Your Hormones Change When You Are Around People",
// "How Growth Hormone Rebuilds You While You Sleep",
// "The Hormone That Makes You Cry For No Reason",
// "Why Your Body Produces Natural Painkillers",
// "How Hunger Hormones Trick Your Brain Into Overeating",
// "The Chemical Your Brain Releases When You Help Someone",
// "Why Your Hormones Make You Crave Junk Food At Night",
// "How Prolactin Makes You Feel Satisfied After Eating",
// "The Hormone That Spikes When You Achieve Something",
// "Why Thyroid Problems Are Mistaken For Laziness",
// "How Your Body Uses Hormones To Signal Danger",

// /* ================= ORGANS & BODY SYSTEMS (25) ================= */
// "The Organ That Works Hardest While You Sleep",
// "Why Your Heart Knows You Are Stressed Before You Do",
// "How Your Liver Performs 500 Functions Every Single Day",
// "The Real Reason Your Stomach Can Digest Itself",
// "Why Your Brain Uses More Energy Than Any Other Organ",
// "How Your Kidneys Filter Your Entire Blood Supply Every Hour",
// "The Shocking Electrical Activity Inside Your Heart",
// "Why Your Lungs Are Never Completely Empty",
// "How Your Skin Replaces Itself Completely Every Month",
// "The Real Reason Your Appendix Is Not Useless",
// "Why Your Eyes See The World Upside Down First",
// "How Your Intestines Would Stretch Over 7 Meters",
// "The Organ That Can Regrow Itself After Being Cut In Half",
// "Why Your Nose Can Detect Over One Trillion Smells",
// "How Your Stomach Acid Can Dissolve Metal",
// "The Real Reason Your Bones Are Stronger Than Steel",
// "Why Your Spleen Is Called The Blood Graveyard",
// "How Your Thyroid Controls Your Entire Personality",
// "The Organ That Has More Nerve Endings Than Your Brain",
// "Why Your Heart Changes Shape Under Extreme Stress",
// "How Your Brain Rewires Itself After An Injury",
// "The Real Reason Your Body Temperature Drops At Night",
// "Why Your Immune System Sometimes Attacks Itself",
// "How Your Pancreas Controls Every Mood You Have",
// "The Shocking Number Of Cells Your Body Destroys Every Second",

// /* ================= UNCOMFORTABLE & SURPRISING FACTS (25) ================= */
// "Uncomfortable Facts About The Human Body Nobody Tells You",
// "The Disgusting Truth About What Happens When You Sleep",
// "Uncomfortable Facts About Your Brain That Will Disturb You",
// "The Truth About What Your Body Does When You Die",
// "Uncomfortable Facts About Food You Eat Every Day",
// "Why Your Body Is Doing Gross Things Right Now",
// "The Shocking Truth About How Dirty Your Mouth Really Is",
// "Uncomfortable Facts About Human Behavior Backed By Science",
// "The Real Reason Doctors Fear These Symptoms",
// "Uncomfortable Facts About Sleep That Will Keep You Awake",
// "The Truth About What Hospitals Never Tell Patients",
// "Why Most People Are Walking Around Malnourished",
// "Uncomfortable Facts About Your Gut That Will Shock You",
// "The Disgusting Reality Of What Happens To Food Inside You",
// "Uncomfortable Truths About Memory Your Brain Hides",
// "Why Your Eyes Are Lying To You Every Second",
// "The Dark Truth About What Stress Does To Your Organs",
// "Uncomfortable Facts About The Air You Are Breathing Right Now",
// "Why Your Body Is Already Dying In Small Ways Every Day",
// "The Truth About How Little Sleep Actually Does To You",
// "Uncomfortable Facts About Pain You Were Never Taught",
// "Why Everything You Know About Healthy Eating Is Wrong",
// "The Shocking Things Happening Inside Your Gut Right Now",
// "Uncomfortable Facts About Your Heart That Will Scare You",
// "Why Your Body Starts Breaking Down After 25",

// /* ================= FOOD & GUT SCIENCE (25) ================= */
// "Why Eating Slowly Is More Powerful Than Any Diet",
// "The Food That Scientists Say Is More Addictive Than Cocaine",
// "How Your Gut Bacteria Controls Your Personality",
// "Why Your Body Craves Specific Foods When Sick",
// "The Real Reason Diets Always Fail Within Weeks",
// "How Ultra Processed Food Rewires Your Brain Permanently",
// "Why Eating At Night Destroys Your Metabolism",
// "The Shocking Amount Of Sugar In Foods Labeled Healthy",
// "How What You Eat Literally Changes Your DNA",
// "Why Spicy Food Triggers A Natural High In Your Brain",
// "How Your Gut Sends Signals Directly To Your Brain",
// "The Real Reason You Feel Tired After Eating",
// "Why Dehydration Is Constantly Mistaken For Hunger",
// "How Fasting For One Day Resets Your Entire System",
// "The Truth About So-Called Superfoods The Industry Hides",
// "Why Your Eyes Control How Much Food You Eat",
// "How Food Companies Engineer Products To Be Physically Addictive",
// "The Real Science Behind Why We Love Comfort Food",
// "Why Coffee Does Not Actually Wake You Up",
// "How Your Childhood Food Habits Are Controlling You Today",
// "The Truth About Fat That Science Got Wrong For Decades",
// "Why Eating Colors Matters More Than Counting Calories",
// "How Your Microbiome Makes Food Decisions Before You Do",
// "The Real Reason You Always Have Room For Dessert",
// "Why Humans Are The Only Animals That Cook Their Food",

// /* ================= DARK PSYCHOLOGY (25) ================= */
// "Dark Psychology Tricks Being Used On You Right Now",
// "Why Your Brain Cannot Tell The Difference Between Real And Imagined",
// "The Real Reason People Follow Cults Without Realizing",
// "How Silence Is Used As A Psychological Weapon",
// "Why You Remember Unfinished Tasks Better Than Completed Ones",
// "The Psychology Of Why People Are Cruel Online",
// "How Power Permanently Changes A Person's Brain",
// "Why People With High IQ Struggle Most With Daily Life",
// "The Real Reason We Cry At Movies But Not Real Life",
// "How Repetition Tricks Your Brain Into Believing Lies",
// "Why Your Subconscious Makes Decisions 7 Seconds Before You Do",
// "The Dark Psychology Behind Why People Cheat",
// "How Anger Can Actually Be Healthy For Your Brain",
// "Why Your Memory Is Far Less Reliable Than You Think",
// "The Real Reason People Love Horror Movies",
// "How Loneliness Physically Damages Your Brain Structure",
// "Why You Feel Guilty Even When You Did Nothing Wrong",
// "How Narcissists Use Kindness As A Weapon",
// "Why You Make Worse Decisions When You Are Hungry",
// "The Real Reason People Are Afraid Of Success",
// "How Advertisers Hijack Your Brain Without You Noticing",
// "Why Your Brain Is Hardwired To Always Expect The Worst",
// "The Real Psychology Behind Why People Ghost Others",
// "How Trauma Physically Rewires Your Brain Forever",
// "Why Being Watched Changes How You Behave Completely",

// /* ================= BODY REACTIONS & DAILY SCIENCE (25) ================= */
// "Why Your Body Jerks Awake When You Are Falling Asleep",
// "The Real Reason You Get Goosebumps From Music",
// "Why Humans Are The Only Animals That Blush",
// "How Your Body Heals A Deep Cut Without You Doing Anything",
// "The Real Reason Your Eyes Are Closed When You Sneeze",
// "Why Your Nose Always Has One Nostril More Open Than The Other",
// "How Your Body Detects Danger Before Your Brain Does",
// "The Real Reason You Forget Why You Walked Into A Room",
// "Why Your Heartbeat Syncs With People You Love",
// "How Your Body Produces Its Own Natural Alcohol",
// "The Real Reason You Get Brain Freeze From Cold Food",
// "Why Holding In A Sneeze Can Actually Kill You",
// "How Laughter Physically Heals Your Body From The Inside",
// "The Real Reason You Feel Pain In A Limb That Is Gone",
// "Why Your Body Knows To Wake Up Before Your Alarm",
// "How Your Body Ages Faster When You Are Lonely",
// "The Real Reason You Feel Exhausted After Doing Nothing",
// "Why Your Heart Beats Faster When You Hear Your Own Name",
// "How Your Body Changes When You Hold Someone's Hand",
// "The Real Reason Your Joints Crack When You Stretch",
// "Why Humans Are The Only Animals That Cry Emotional Tears",
// "How Your Body Burns Calories Even While Sitting Still",
// "The Real Reason You Feel More Pain When You Expect It",
// "Why Your Eyes Move Rapidly When You Are Dreaming",
// "How Your Body Tells You It Needs Water Before You Feel Thirsty",

// ];
// let availableTopics = [];

// function shuffle(array) {
//   for (let i = array.length - 1; i > 0; i--) {
//     const j = Math.floor(Math.random() * (i + 1));
//     [array[i], array[j]] = [array[j], array[i]];
//   }
//   return array;
// }

// function getRandomTopic() {
//   if (availableTopics.length === 0) {
//     availableTopics = shuffle([...topics]);
//     console.log("All topics used. Resetting topic list...");
//   }

//   return availableTopics.pop();
// }

// module.exports = { getRandomTopic };




// // // mixedAudienceTopicsManager.js

// // const topics = [

// // /* ===== SEX / RELATIONSHIP / HEALTH FACTS (Educational) ===== */

// // "Interesting Facts About Human Reproduction",
// // "Why Physical Intimacy Improves Mental Health",
// // "Facts About Hormones And Relationships",
// // "Why Communication Is Important In Relationships",
// // "The Science Behind Attraction",
// // "Why Couples Who Laugh Together Stay Together",
// // "How Love Affects Your Brain",
// // "Why Trust Is Important In Relationships",
// // "Facts About Marriage And Happiness",
// // "How Emotional Connection Strengthens Relationships",
// // "Why People Fall In Love",
// // "How Relationships Affect Mental Health",
// // "The Psychology Of Romantic Attraction",
// // "Why Respect Matters In Relationships",
// // "How Healthy Relationships Improve Life",
// // "Why Companionship Is Important For Humans",
// // "The Science Of Emotional Bonding",
// // "Why Love Reduces Stress",
// // "How Relationships Improve Longevity",
// // "The Benefits Of Emotional Support",

// // /* ===== OLD AGE / SENIOR FACTS ===== */

// // "Healthy Habits For People Over 60",
// // "Why Walking Is Important In Old Age",
// // "Foods That Improve Memory In Seniors",
// // "How To Stay Active After 70",
// // "Why Social Interaction Is Important For Seniors",
// // "Daily Exercises For Older Adults",
// // "How To Maintain Brain Health In Old Age",
// // "Why Sleep Is Important For Seniors",
// // "Tips To Stay Healthy After Retirement",
// // "How Reading Improves Memory In Old Age",
// // "Why Laughter Is Important For Seniors",
// // "How To Prevent Memory Loss Naturally",
// // "Healthy Diet Tips For Elderly People",
// // "Why Staying Busy Improves Longevity",
// // "How To Maintain Strength In Old Age",
// // "Why Seniors Need Regular Checkups",
// // "How To Improve Balance In Old Age",
// // "Why Hydration Is Important For Seniors",
// // "How To Stay Mentally Active After 65",
// // "Why Positive Thinking Improves Health In Old Age",

// // /* ===== CHILDREN / FAMILY CONTENT ===== */

// // "Why Children Learn Faster Than Adults",
// // "How Kids Develop Creativity",
// // "Fun Facts About Children's Brain",
// // "Why Play Is Important For Child Development",
// // "How Reading Helps Children Grow",
// // "Why Kids Ask So Many Questions",
// // "How Parents Influence Child Behavior",
// // "Why Children Need Proper Sleep",
// // "How Storytelling Improves Learning",
// // "Why Kids Love Cartoons",
// // "How Children Learn New Skills Quickly",
// // "Why Encouragement Builds Confidence In Kids",
// // "How Games Help Children Learn",
// // "Why Positive Parenting Matters",
// // "How Kids Develop Social Skills",
// // "Why Curiosity Is Important For Children",
// // "How Music Helps Children Learn",
// // "Why Outdoor Play Is Important",
// // "How Children Build Friendships",
// // "Why Kids Need Healthy Food",

// // /* ===== ANIMAL STORIES (Very Viral) ===== */

// // "Heartwarming Story Of A Loyal Dog",
// // "How Elephants Remember Their Families",
// // "Why Dogs Are Called Man's Best Friend",
// // "Amazing Story Of A Cat Saving Its Owner",
// // "How Dolphins Help Humans In Danger",
// // "Why Lions Protect Their Cubs",
// // "Story Of A Dog Waiting For Its Owner",
// // "How Birds Find Their Way Home",
// // "Incredible Story Of A Brave Horse",
// // "Why Penguins Stay Together For Life",
// // "How Wolves Work As A Team",
// // "Story Of A Dog Rescuing A Child",
// // "Why Elephants Never Forget",
// // "How Monkeys Help Each Other",
// // "Amazing Story Of A Loyal Animal",
// // "How Animals Show Love",
// // "Why Dogs Protect Their Owners",
// // "Story Of A Kind Farmer And His Cow",
// // "How Animals Recognize Humans",
// // "Inspiring Story Of A Rescue Dog",

// // /* ===== GENERAL LIFE / FEEL-GOOD STORIES ===== */

// // "Simple Habits That Make Life Happier",
// // "Why Helping Others Improves Happiness",
// // "How Gratitude Improves Mental Health",
// // "Why Smiling Improves Mood",
// // "How Kindness Changes Lives",
// // "Why Positive Thinking Matters",
// // "How Daily Exercise Improves Health",
// // "Why Drinking Water Is Important",
// // "How Small Habits Create Big Success",
// // "Why Sleep Is Important For Health",
// // "How Reading Improves Brain Function",
// // "Why Walking Improves Heart Health",
// // "How Good Friends Improve Life",
// // "Why Family Support Matters",
// // "How Staying Active Improves Energy",
// // "Why Learning New Skills Keeps Brain Young",
// // "How Listening Improves Relationships",
// // "Why Patience Leads To Success",
// // "How Consistency Builds Confidence",
// // "Why Helping Others Makes You Happy",

// // /* ===== FUN FACTS FOR ALL AGES ===== */

// // "Interesting Facts About The Human Brain",
// // "Why We Dream At Night",
// // "How The Heart Works",
// // "Why We Feel Hungry",
// // "How The Brain Stores Memories",
// // "Why We Feel Tired",
// // "How The Body Heals Itself",
// // "Why We Feel Happy",
// // "How The Immune System Protects Us",
// // "Why We Feel Pain",
// // "How The Brain Controls The Body",
// // "Why We Feel Fear",
// // "How The Body Uses Energy",
// // "Why We Feel Sleepy",
// // "How The Brain Sends Signals",
// // "Why We Feel Excited",
// // "How The Body Maintains Balance",
// // "Why We Feel Cold",
// // "How The Brain Processes Information",
// // "Why We Feel Thirsty"

// // ];

// // let availableTopics = [];

// // function shuffle(array) {
// //   for (let i = array.length - 1; i > 0; i--) {
// //     const j = Math.floor(Math.random() * (i + 1));
// //     [array[i], array[j]] = [array[j], array[i]];
// //   }
// //   return array;
// // }

// // function getRandomTopic() {
// //   if (availableTopics.length === 0) {
// //     availableTopics = shuffle([...topics]);





// //     console.log("All topics used. Resetting topic list...");
// //   }

// //   return availableTopics.pop();







const topics = [
  /* ================= DARK PSYCHOLOGY & HIDDEN MANIPULATION (30) ================= */
  "The psychological trick to make anyone regret losing you",
  "How to tell if someone is secretly studying you",
  "The dangerous power of silence in any conversation",
  "How toxic people use 'love bombing' to control you",
  "The dark psychology behind the 'push and pull' method",
  "Why being too nice makes people respect you less",
  "How to spot a manipulator in the first 5 minutes",
  "The psychological reason why people lie to your face",
  "How to use reverse psychology to get what you want",
  "The dark truth about why narcissists choose you",
  "How to read someone's true intentions through their eyes",
  "The silent manipulation trick that makes you doubt yourself",
  "Why people ghost you when things are going well",
  "The psychological trigger that makes people obsessed with you",
  "How to make someone feel guilty without saying a word",
  "The hidden signs that someone is secretly jealous of you",
  "How to win any argument by staying completely calm",
  "The dark psychology of ignoring someone on purpose",
  "Why people crave validation from those who reject them",
  "How to spot a fake smile in less than a second",
  "The psychological power of never reacting to insults",
  "How to use the 'Ben Franklin effect' to make enemies like you",
  "Why manipulators always make you feel like the bad guy",
  "The scary truth about how advertisements control your choices",
  "How to detect a lie by watching someone's hands",
  "Why people who speak less always hold more power",
  "The dark psychology behind why people stay in toxic cycles",
  "How to make anyone feel instant regret for disrespecting you",
  "The psychological danger of sharing your goals too early",
  "How to protect your mind from subliminal manipulation",

  /* ================= HIDDEN ATTRACTION & CHEMISTRY SECRETS (30) ================= */
  "How to tell if someone is secretly attracted to you",
  "The chemical reason why eye contact feels so intense",
  "Why we fall for people who resemble our parents",
  "The psychological sign that someone is thinking about you",
  "Why we are attracted to people who ignore us",
  "How to create instant chemistry with a stranger",
  "Why laughing together is the ultimate attraction trigger",
  "The psychological reason why breakups hurt physically",
  "Signs that someone is secretly in love with you",
  "Why playing hard to get actually works on the brain",
  "How to know if someone is mirroring your body language",
  "The scent of attraction: How your body chooses a partner",
  "Why couples start speaking in the same voice over time",
  "The psychological trick of maintaining mysterious vibes",
  "Why we get butterflies in our stomach around someone we like",
  "How your brain reacts to a hug from someone you trust",
  "The real reason why chemistry fades in long relationships",
  "Signs that someone is trying to hide their feelings for you",
  "How your heart rate syncs with the person you love",
  "Why we idealize people before we actually know them",
  "The psychological impact of holding hands with a partner",
  "Why rejection makes you want the person even more",
  "The silent signs of deep emotional attachment",
  "How to tell the difference between love and obsession",
  "Why physical touch reduces stress in under 20 seconds",
  "The science of why opposites attract (and why they clash)",
  "How to make yourself instantly more memorable to others",
  "The psychology behind why we write long paragraphs when in love",
  "Why a simple smile is the most powerful attraction tool",
  "How emotional validation makes someone fall for you faster",

  /* ================= PHYSICAL INTIMACY & RELATIONSHIP SCIENCE (30) ================= */
  "The scientific reason why kissing boosts your immune system",
  "Why human skin becomes more sensitive during physical intimacy",
  "The hormone that causes the cuddle chemical effect after intimacy",
  "Why holding hands with a loved one instantly reduces physical pain",
  "The biological reason why morning intimacy improves your mood all day",
  "How a single touch can lower blood pressure in seconds",
  "Why some smells make humans instantly attracted to each other",
  "What happens to your brain chemistry during a 20-second hug",
  "The surprising health benefits of regular physical intimacy",
  "How pupil dilation reveals true physical attraction instantly",
  "Why your heart rate syncs perfectly with someone you are attracted to",
  "The scientific reason why eye contact makes you feel warm inside",
  "How the brain processes physical touch compared to other senses",
  "Why dopamine spikes during the early stages of attraction",
  "The biological difference between infatuation and long-term bonding",
  "How physical intimacy improves sleep quality and reduces insomnia",
  "The role of pheromones in human partner selection",
  "Why physical closeness reduces cortisol levels in the body",
  "The surprising science behind why humans kiss",
  "How your nervous system reacts to a gentle touch on the neck",
  "Why skin-to-skin contact is vital for newborn brain development",
  "The chemical cocktail released in your body when you fall in love",
  "Why physical intimacy is proven to boost memory and brain function",
  "How your voice pitch changes when talking to someone you find attractive",
  "The connection between regular physical connection and a longer lifespan",
  "Why rejection by a partner triggers the same brain area as physical pain",
  "The science of how touch signals comfort to an anxious brain",
  "Why humans are one of the few species that form monogamous bonds",
  "How your body temperature changes during close physical contact",
  "The evolutionary reason behind human attraction cues",

  /* ================= WHOLESOME CONNECTIONS & KINDNESS FACTS (30) ================= */
  "How helping others releases the same chemicals as eating chocolate",
  "Why yawning when someone else yawns is a sign of high empathy",
  "How looking at cute animal photos increases your focus and productivity",
  "Why smiling—even when fake—tricks your brain into feeling happy",
  "The scientific reason why acts of kindness make you live longer",
  "How your dog's brain chemistry changes when they look at you",
  "Why laughing with friends releases natural painkillers in your brain",
  "The psychological power of receiving an unexpected card or letter",
  "Why hearing your name spoken in a kind voice calms your nervous system",
  "How doing one random act of kindness boosts your immune system for days",
  "Why human babies are hardwired to cooperate and share from birth",
  "How practicing daily gratitude physically changes your brain's structure",
  "Why hugging a tree or spending time in nature reduces stress instantly",
  "The science of how a mother's voice can soothe a child from miles away",
  "Why volunteering reduces rates of depression and anxiety in seniors",
  "How a gentle reassuring tap on the shoulder can boost performance",
  "Why couples who laugh together stay together longer",
  "The neurological reason why giving a gift feels better than receiving one",
  "How kind words from a stranger can elevate your mood for a whole week",
  "Why thinking about a loved one's face can help you tolerate pain",
  "How listening to happy music makes you perceive other people as friendlier",
  "Why dogs can sense when their owners are sad and try to comfort them",
  "The biological reason why we feel warm inside when witnessing kindness",
  "How emotional support from friends speeds up physical healing",
  "Why holding your partner's hand during stressful tasks stabilizes your heart",
  "Why kind people are scientifically proven to have healthier hearts",
  "How positive thinking changes the way your body fights off infections",
  "Why children who grow up with pets have higher self-esteem",
  "The power of validation: Why feeling heard is crucial for mental health",
  "Why being kind to yourself is the first step to reducing stress",

  /* ================= SUBCONSCIOUS MIND & BRAIN SECRETS (30) ================= */
  "Why your brain makes decisions 7 seconds before you do",
  "How to reprogram your subconscious mind before sleep",
  "The weird reason why you remember bad memories better",
  "Why high IQ people struggle to sleep at night",
  "How to trick your brain into stopping procrastination",
  "The psychology of why you talk to yourself in your head",
  "How silence physically changes your brain structure",
  "Why you always remember unfinished tasks more",
  "The psychological trick to cure overthinking in 2 minutes",
  "Why your brain cannot tell the difference between real and imagined",
  "How power permanently changes the neurobiology of a person",
  "Why you hate the sound of your own recorded voice",
  "The science of why boredom is actually good for you",
  "How stress physically shrinks the size of your brain",
  "Why you make terrible decisions when you are hungry",
  "The real reason why you feel watched when alone",
  "How to unlock deep focus using the 90-minute rule",
  "Why your memory is far less reliable than you think",
  "The psychology behind why we love horror movies",
  "How nostalgia tricks your brain into feeling happy and sad",
  "Why some people are natural born leaders (according to science)",
  "How to use music to instantly unlock forgotten memories",
  "Why you can lie more easily in texts than in person",
  "The psychological danger of sleep deprivation on decision making",
  "Why your brain is hardwired to expect the worst outcome",
  "How complaining physically rewires your brain to be negative",
  "The shocking effect of a simple compliment on your brain",
  "Why you feel anxious for absolutely no reason at all",
  "How your subconscious mind solves problems while you sleep",
  "The science of why humans have a strong need to belong",

  /* ================= DISTURBING & UNCOMFORTABLE TRUTHS (30) ================= */
  "Uncomfortable facts about the human body nobody tells you",
  "The disturbing truth about what happens when you sleep",
  "Uncomfortable facts about your brain that will scare you",
  "What your body actually does in the first hour after death",
  "The creepy reality of what happens inside your gut",
  "Why your eyes are technically lying to you every second",
  "Uncomfortable facts about human behavior backed by science",
  "The dark truth about what chronic stress does to your organs",
  "Why everything you know about sleep might be wrong",
  "The disgusting truth about how dirty your phone screen really is",
  "Uncomfortable facts about memory that will make you doubt yourself",
  "Why your body starts breaking down slowly after age 25",
  "The scary reality of sleep paralysis and why it happens",
  "Why most people are walking around clinically malnourished",
  "The shocking amount of microplastics in our vital organs",
  "Uncomfortable truths about how easily your brain can be brainwashed",
  "Why humans are the only animals that willingly destroy their sleep",
  "The disturbing reason why you get chills from certain music",
  "What happens to your brain when you ignore your emotions",
  "The dark side of empathy: Why feeling too much can ruin you",
  "Uncomfortable facts about how pain is created in the brain",
  "Why your body is constantly killing cancer cells every second",
  "The real reason doctors are worried about your daily posture",
  "Why sitting for 8 hours is officially called the new smoking",
  "The alarming truth about how energy drinks damage your heart",
  "Why your brain blocks out the smell of your own home",
  "The uncomfortable reason why we judge people instantly",
  "Why your body temperature drops right before you fall asleep",
  "The dark reality of how loneliness physically shortens your life",
  "Why you feel completely exhausted after doing absolutely nothing",

  /* ================= BODY REACTIONS & DAILY SCIENCE (30) ================= */
  "Why your body jerks awake when you are falling asleep",
  "Why you always wake up at 3 AM (The scientific explanation)",
  "Why humans are the only animals that blush",
  "How your body heals a deep cut with zero conscious effort",
  "The real reason why your eyes close when you sneeze",
  "Why your nose always has one nostril more active than the other",
  "How your body detects danger before your brain even registers it",
  "The real reason why you get butterflies in your stomach",
  "Why your voice sounds completely different to other people",
  "How your gut bacteria controls your mood and cravings",
  "Why your heart rate changes when you are nervous or excited",
  "Why holding in a sneeze can actually be dangerous",
  "How laughter physically heals your body from the inside",
  "Why you feel pain in a limb that is no longer there",
  "How your body knows to wake up exactly before your alarm",
  "Why your joints make cracking sounds when you stretch",
  "Why humans are the only species that cry emotional tears",
  "How your body burns calories even when you are sitting still",
  "Why you feel more pain when you are expecting it to hurt",
  "Why your eyes move rapidly when you are dreaming",
  "Why your feet smell worse than almost any other body part",
  "How your body signals dehydration before you feel thirsty",
  "Why you get brain freeze when eating cold food too fast",
  "Why your skin wrinkles after staying in water too long",
  "Why you sweat even when you are not physically hot",
  "Why you cannot tickle yourself (The neurological reason)",
  "Why yawning is so contagious to the human brain",
  "How deep breathing instantly resets your nervous system",
  "Why physical intimacy is critical for your overall immune system",
  "Why your body temperature spikes when you have an infection",

  /* ================= HORMONES & BODY CHEMISTRY (25) ================= */
  "Why cortisol is slowly destroying your body from within",
  "How dopamine makes you addicted to endless scrolling",
  "The chemical that makes you trust absolute strangers",
  "Why adrenaline gives people superhuman strength in emergencies",
  "How serotonin controls your happiness and mood",
  "Why your hormones crash when you reach age 30",
  "Why melatonin does way more than just help you sleep",
  "How insulin controls your energy levels and fat storage",
  "The hormone that makes you feel completely empty inside",
  "Why testosterone is not just a male hormone",
  "How estrogen affects your brain structure every single day",
  "The exact chemical behind every panic attack you experience",
  "How growth hormone repairs your tissues while you sleep",
  "The hormone that triggers crying for absolutely no reason",
  "How hunger hormones trick your brain into overeating",
  "The chemical released in your brain when you help someone",
  "Why thyroid issues are constantly mistaken for laziness",
  "How prolactin makes you feel satisfied after eating food",
  "The hormone that spikes when you achieve a difficult goal",
  "How your body uses hormones to signal immediate danger",
  "How sugar spikes dopamine just like an addictive drug",
  "Why chronic high cortisol makes it impossible to lose weight",
  "How oxytocin builds deep trust in under 30 seconds",
  "The chemical reason why some people are always stressed",
  "How lack of sleep completely destroys your hormone balance",

  /* ================= FOOD & GUT SCIENCE (25) ================= */
  "Why eating slowly is more powerful than any diet plan",
  "The food that scientists say is more addictive than cocaine",
  "How your gut microbiome dictates your food decisions",
  "Why your body craves specific foods when you are sick",
  "The real reason why diets always fail within three weeks",
  "How ultra-processed food rewires your brain permanently",
  "Why eating late at night completely destroys your metabolism",
  "The shocking amount of sugar hidden in 'healthy' foods",
  "How what you eat literally changes your DNA expression",
  "Why spicy food triggers a natural high in your brain",
  "How your gut sends signals directly to your brain via the vagus nerve",
  "The real scientific reason why you feel tired after eating",
  "Why mild dehydration is constantly mistaken for hunger",
  "How fasting for 24 hours resets your entire immune system",
  "The truth about superfoods that the industry hides from you",
  "Why your eyes control how much food you actually eat",
  "How food companies design products to be physically addictive",
  "The real science behind why we love comfort food so much",
  "Why coffee does not actually wake you up (It just blocks sleepiness)",
  "How your childhood food habits control your cravings today",
  "The truth about dietary fat that science got wrong for decades",
  "Why eating colorful foods is more important than counting calories",
  "The real reason why you always have room for sweet dessert",
  "Why humans are the only animals that cook their food",
  "How drinking cold water with meals affects your digestion"
];

let availableTopics = [];

function shuffle(array) {
  const newArray = [...array];
  for (let i = newArray.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [newArray[i], newArray[j]] = [newArray[j], newArray[i]];
  }
  return newArray;
}

function getRandomTopic() {
  if (availableTopics.length === 0) {
    availableTopics = shuffle(topics);
    console.log(`Resetting topic pool with ${topics.length} viral topics.`);
  }

  return availableTopics.pop();
}

module.exports = { getRandomTopic, topics };
// // }

// // module.exports = { getRandomTopic };
